#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://101.200.216.3:3306/db_user?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://101.200.216.3:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.imooc.course

server:
  thrift:
    user:
      ip: user-service
      port: 7911
