version: '3'

networks:
  default:
    external:
      name: imooc-network

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
    - "--mysql.address=172.24.58.200"

  user-edge-service:
    image: user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=172.24.58.200"

  course-service:
    image: course-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=172.24.58.200"
    - "--zookeeper.address=172.24.58.200"

  course-edge-service:
    image: course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=172.24.58.200"

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
    - course-edge-service
    - user-edge-service
    ports:
    - 80:80