server:
  port: 8081

spring:
  dubbo:
    application.name: course-service
    registry.address: zookeeper://192.168.1.8:2181
    scan: com.imooc.course

user:
  edge:
    service:
      addr: user-service:8082

